#include "cc1101_types.h"

extern cc1101_registers_definitions_t _cc1101_registers_def;

typedef enum
{
    CC1101_INTERNAL_REG_ADDRESS_IOCFG2 = 0x00,    // 0x00
    CC1101_INTERNAL_REG_ADDRESS_IOCFG1,           // 0x01
    CC1101_INTERNAL_REG_ADDRESS_IOCFG0,           // 0x02
    CC1101_INTERNAL_REG_ADDRESS_FIFOTHR,          // 0x03
    CC1101_INTERNAL_REG_ADDRESS_SYNC1,            // 0x04
    CC1101_INTERNAL_REG_ADDRESS_SYNC0,            // 0x05
    CC1101_INTERNAL_REG_ADDRESS_PKTLEN,           // 0x06
    CC1101_INTERNAL_REG_ADDRESS_PKTCTRL1,         // 0x07
    CC1101_INTERNAL_REG_ADDRESS_PKTCTRL0,         // 0x08
    CC1101_INTERNAL_REG_ADDRESS_ADDR,             // 0x09
    CC1101_INTERNAL_REG_ADDRESS_CHANNR,           // 0x0A
    CC1101_INTERNAL_REG_ADDRESS_FSCTRL1,          // 0x0B
    CC1101_INTERNAL_REG_ADDRESS_FSCTRL0,          // 0x0C
    CC1101_INTERNAL_REG_ADDRESS_FREQ2,            // 0x0D
    CC1101_INTERNAL_REG_ADDRESS_FREQ1,            // 0x0E
    CC1101_INTERNAL_REG_ADDRESS_FREQ0,            // 0x0F
    CC1101_INTERNAL_REG_ADDRESS_MDMCFG4,          // 0x10
    CC1101_INTERNAL_REG_ADDRESS_MDMCFG3,          // 0x11
    CC1101_INTERNAL_REG_ADDRESS_MDMCFG2,          // 0x12
    CC1101_INTERNAL_REG_ADDRESS_MDMCFG1,          // 0x13
    CC1101_INTERNAL_REG_ADDRESS_MDMCFG0,          // 0x14
    CC1101_INTERNAL_REG_ADDRESS_DEVIATN,          // 0x15
    CC1101_INTERNAL_REG_ADDRESS_MCSM2,            // 0x16
    CC1101_INTERNAL_REG_ADDRESS_MCSM1,            // 0x17
    CC1101_INTERNAL_REG_ADDRESS_MCSM0,            // 0x18
    CC1101_INTERNAL_REG_ADDRESS_FOCCFG,           // 0x19
    CC1101_INTERNAL_REG_ADDRESS_BSCFG,            // 0x1A
    CC1101_INTERNAL_REG_ADDRESS_AGCCTRL2,         // 0x1B
    CC1101_INTERNAL_REG_ADDRESS_AGCCTRL1,         // 0x1C
    CC1101_INTERNAL_REG_ADDRESS_AGCCTRL0,         // 0x1D
    CC1101_INTERNAL_REG_ADDRESS_WOREVT1,          // 0x1E
    CC1101_INTERNAL_REG_ADDRESS_WOREVT0,          // 0x1F
    CC1101_INTERNAL_REG_ADDRESS_WORCTRL,          // 0x20
    CC1101_INTERNAL_REG_ADDRESS_FREND1,           // 0x21
    CC1101_INTERNAL_REG_ADDRESS_FREND0,           // 0x22
    CC1101_INTERNAL_REG_ADDRESS_FSCAL3,           // 0x23
    CC1101_INTERNAL_REG_ADDRESS_FSCAL2,           // 0x24
    CC1101_INTERNAL_REG_ADDRESS_FSCAL1,           // 0x25
    CC1101_INTERNAL_REG_ADDRESS_FSCAL0,           // 0x26
    CC1101_INTERNAL_REG_ADDRESS_RCCTRL1,          // 0x27
    CC1101_INTERNAL_REG_ADDRESS_RCCTRL0,          // 0x28
    CC1101_INTERNAL_REG_ADDRESS_FSTEST,           // 0x29
    CC1101_INTERNAL_REG_ADDRESS_PTEST,            // 0x2A
    CC1101_INTERNAL_REG_ADDRESS_AGCTEST,          // 0x2B
    CC1101_INTERNAL_REG_ADDRESS_TEST2,            // 0x2C
    CC1101_INTERNAL_REG_ADDRESS_TEST1,            // 0x2D
    CC1101_INTERNAL_REG_ADDRESS_TEST0,            // 0x2E
    /*****************************************/

    /* Address 0x30; Strobe CMD SRES(Write/Read) or PARTNUM(BURST READ)*/
    CC1101_INTERNAL_REG_ADDRESS_SRES_PARTNUM    =   0x30,
    /* Address 0x31; Strobe CMD SFSTXON(Write/Read) or VERSION(BURST READ)*/
    CC1101_INTERNAL_REG_ADDRESS_SFSTXON_VERSION,
    /* Address 0x32; Strobe CMD SXOFF(Write/Read) or FREQEST(BURST READ)*/
    CC1101_INTERNAL_REG_ADDRESS_SXOFF_FREQEST,
    /* Address 0x33; Strobe CMD SCAL(Write/Read) or LQI(BURST READ)*/
    CC1101_INTERNAL_REG_ADDRESS_SCAL_LQI,
    /* Address 0x34; Strobe CMD SRX(Write/Read) or RSSI(BURST READ)*/
    CC1101_INTERNAL_REG_ADDRESS_SRX_RSSI,
    /* Address 0x35; Strobe CMD STX(Write/Read) or MARCSTATE(BURST READ)*/         
    CC1101_INTERNAL_REG_ADDRESS_STX_MARCSTATE,
    /* Address 0x36; Strobe CMD SIDLE(Write/Read) or WORTIME1(BURST READ)*/
    CC1101_INTERNAL_REG_ADDRESS_SIDLE_WORTIME1,
    /* Address 0x37; WORTIME0(BURST READ)*/
    CC1101_INTERNAL_REG_ADDRESS_WORTIME0,
    /* Address 0x38; Strobe CMD SWOR(Write/Read) or PKTSTATUS(BURST READ)*/
    CC1101_INTERNAL_REG_ADDRESS_SWOR_PKTSTATUS,
    /* Address 0x39; Strobe CMD SPWD(Write/Read) or VCO_VC_DAC(BURST READ)*/
    CC1101_INTERNAL_REG_ADDRESS_SPWD_VCO_VC_DAC,
    /* Address 0x40; Strobe CMD SFRX(Write/Read) or TXBYTES(BURST READ)*/
    CC1101_INTERNAL_REG_ADDRESS_SFRX_TXBYTES,
    /* Address 0x41; Strobe CMD SFTX(Write/Read) or RXBYTES(BURST READ)*/
    CC1101_INTERNAL_REG_ADDRESS_SFTX_RXBYTES,
    /* Address 0x42; Strobe CMD SWORRST(Write/Read) or RCCTRL1_STATUS(BURST READ)*/
    CC1101_INTERNAL_REG_ADDRESS_SWORRST_RCCTRL1_STATUS,
    /* Address 0x43; Strobe CMD SNOP(Write/Read) or RCCTRL0_STATUS(BURST READ)*/
    CC1101_INTERNAL_REG_ADDRESS_SNOP_RCCTRL0_STATUS,
    /* Address 0x44; PATABLE(Write/Read)*/
    CC1101_INTERNAL_REG_ADDRESS_PATABLE,
    /* Address 0x45; TXFIFO(Write) or RXFIFO(READ)*/
    CC1101_INTERNAL_REG_ADDRESS_TXFIFO_RXFIFO,

}cc1101_reg_address_t;



const cc1101_trans_reg_t translation_regs[]  =   {
    { .reg_addr = 0xFF, .reg_type = CC1101_REG_TYPE_MARKER, .reg_access_type = CC1101_REG_ACCESS_TYPE_UNKNOWN },
    { .reg_struct = &_cc1101_registers_def.iocfg2, .reg_addr = CC1101_INTERNAL_REG_ADDRESS_IOCFG2, .reg_type = CC1101_REG_TYPE_CONFIG, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_WRITE },
    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_IOCFG1, .reg_type = CC1101_REG_TYPE_CONFIG, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_WRITE },
    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_IOCFG0, .reg_type = CC1101_REG_TYPE_CONFIG, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_WRITE },

    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_FIFOTHR, .reg_type = CC1101_REG_TYPE_CONFIG, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_MOD_WRITE },

    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_SYNC1, .reg_type = CC1101_REG_TYPE_CONFIG, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_WRITE },
    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_SYNC0, .reg_type = CC1101_REG_TYPE_CONFIG, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_WRITE },
    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_PKTLEN, .reg_type = CC1101_REG_TYPE_CONFIG, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_WRITE },

    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_PKTCTRL1, .reg_type = CC1101_REG_TYPE_CONFIG, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_MOD_WRITE },
    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_PKTCTRL0, .reg_type = CC1101_REG_TYPE_CONFIG, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_MOD_WRITE },

    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_ADDR, .reg_type = CC1101_REG_TYPE_CONFIG, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_WRITE },
    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_CHANNR, .reg_type = CC1101_REG_TYPE_CONFIG, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_WRITE },

    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_FSCTRL1, .reg_type = CC1101_REG_TYPE_CONFIG, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_MOD_WRITE },

    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_FSCTRL0, .reg_type = CC1101_REG_TYPE_CONFIG, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_WRITE },

    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_FREQ2, .reg_type = CC1101_REG_TYPE_CONFIG, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_MOD_WRITE },

    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_FREQ1, .reg_type = CC1101_REG_TYPE_CONFIG, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_WRITE },
    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_FREQ0, .reg_type = CC1101_REG_TYPE_CONFIG, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_WRITE },
    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_MDMCFG4, .reg_type = CC1101_REG_TYPE_CONFIG, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_WRITE },
    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_MDMCFG3, .reg_type = CC1101_REG_TYPE_CONFIG, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_WRITE },
    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_MDMCFG2, .reg_type = CC1101_REG_TYPE_CONFIG, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_WRITE },

    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_MDMCFG1, .reg_type = CC1101_REG_TYPE_CONFIG, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_MOD_WRITE },

    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_MDMCFG0, .reg_type = CC1101_REG_TYPE_CONFIG, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_WRITE },

    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_DEVIATN, .reg_type = CC1101_REG_TYPE_CONFIG, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_MOD_WRITE },

    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_MCSM2, .reg_type = CC1101_REG_TYPE_CONFIG, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_MOD_WRITE },

    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_MCSM1, .reg_type = CC1101_REG_TYPE_CONFIG, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_MOD_WRITE },

    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_MCSM0, .reg_type = CC1101_REG_TYPE_CONFIG, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_MOD_WRITE },

    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_FOCCFG, .reg_type = CC1101_REG_TYPE_CONFIG, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_MOD_WRITE },

    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_BSCFG, .reg_type = CC1101_REG_TYPE_CONFIG, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_WRITE },
    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_AGCCTRL2, .reg_type = CC1101_REG_TYPE_CONFIG, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_WRITE },

    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_AGCCTRL1, .reg_type = CC1101_REG_TYPE_CONFIG, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_MOD_WRITE },

    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_AGCCTRL0, .reg_type = CC1101_REG_TYPE_CONFIG, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_WRITE },
    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_WOREVT1, .reg_type = CC1101_REG_TYPE_CONFIG, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_WRITE },
    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_WOREVT0, .reg_type = CC1101_REG_TYPE_CONFIG, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_WRITE },

    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_WORCTRL, .reg_type = CC1101_REG_TYPE_CONFIG, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_MOD_WRITE },

    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_FREND1, .reg_type = CC1101_REG_TYPE_CONFIG, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_WRITE },

    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_FREND0, .reg_type = CC1101_REG_TYPE_CONFIG, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_MOD_WRITE },

    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_FSCAL3, .reg_type = CC1101_REG_TYPE_CONFIG, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_WRITE },

    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_FSCAL2, .reg_type = CC1101_REG_TYPE_CONFIG, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_MOD_WRITE },

    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_FSCAL1, .reg_type = CC1101_REG_TYPE_CONFIG, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_MOD_WRITE },
    
    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_FSCAL0, .reg_type = CC1101_REG_TYPE_CONFIG, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_MOD_WRITE },

    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_RCCTRL1, .reg_type = CC1101_REG_TYPE_CONFIG, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_MOD_WRITE },

    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_RCCTRL0, .reg_type = CC1101_REG_TYPE_CONFIG, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_MOD_WRITE },

    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_FSTEST, .reg_type = CC1101_REG_TYPE_CONFIG, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_WRITE },
    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_PTEST, .reg_type = CC1101_REG_TYPE_CONFIG, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_WRITE },
    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_AGCTEST, .reg_type = CC1101_REG_TYPE_CONFIG, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_WRITE },
    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_TEST2, .reg_type = CC1101_REG_TYPE_CONFIG, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_WRITE },
    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_TEST1, .reg_type = CC1101_REG_TYPE_CONFIG, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_WRITE },
    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_TEST0, .reg_type = CC1101_REG_TYPE_CONFIG, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_WRITE },

    /**************************** Strobe Commands ******************************/
    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_SRES_PARTNUM, .reg_type = CC1101_REG_TYPE_STROBE_CMD, .reg_access_type = CC1101_REG_ACCESS_TYPE_WRITE_ONLY },
    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_SFSTXON_VERSION, .reg_type = CC1101_REG_TYPE_STROBE_CMD, .reg_access_type = CC1101_REG_ACCESS_TYPE_WRITE_ONLY },
    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_SXOFF_FREQEST, .reg_type = CC1101_REG_TYPE_STROBE_CMD, .reg_access_type = CC1101_REG_ACCESS_TYPE_WRITE_ONLY },
    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_SCAL_LQI, .reg_type = CC1101_REG_TYPE_STROBE_CMD, .reg_access_type = CC1101_REG_ACCESS_TYPE_WRITE_ONLY },
    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_SRX_RSSI, .reg_type = CC1101_REG_TYPE_STROBE_CMD, .reg_access_type = CC1101_REG_ACCESS_TYPE_WRITE_ONLY },
    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_STX_MARCSTATE, .reg_type = CC1101_REG_TYPE_STROBE_CMD, .reg_access_type = CC1101_REG_ACCESS_TYPE_WRITE_ONLY },
    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_SIDLE_WORTIME1, .reg_type = CC1101_REG_TYPE_STROBE_CMD, .reg_access_type = CC1101_REG_ACCESS_TYPE_WRITE_ONLY },
    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_SWOR_PKTSTATUS, .reg_type = CC1101_REG_TYPE_STROBE_CMD, .reg_access_type = CC1101_REG_ACCESS_TYPE_WRITE_ONLY },
    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_SPWD_VCO_VC_DAC, .reg_type = CC1101_REG_TYPE_STROBE_CMD, .reg_access_type = CC1101_REG_ACCESS_TYPE_WRITE_ONLY },
    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_SFRX_TXBYTES, .reg_type = CC1101_REG_TYPE_STROBE_CMD, .reg_access_type = CC1101_REG_ACCESS_TYPE_WRITE_ONLY },
    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_SFTX_RXBYTES, .reg_type = CC1101_REG_TYPE_STROBE_CMD, .reg_access_type = CC1101_REG_ACCESS_TYPE_WRITE_ONLY },
    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_SWORRST_RCCTRL1_STATUS, .reg_type = CC1101_REG_TYPE_STROBE_CMD, .reg_access_type = CC1101_REG_ACCESS_TYPE_WRITE_ONLY },
    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_SNOP_RCCTRL0_STATUS, .reg_type = CC1101_REG_TYPE_STROBE_CMD, .reg_access_type = CC1101_REG_ACCESS_TYPE_WRITE_ONLY },
    /************************************************************************/
    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_PATABLE, .reg_type = CC1101_REG_TYPE_PATABLE, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_WRITE },

    /************************** TX FIFO - Write Only ************************/
    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_TXFIFO_RXFIFO, .reg_type = CC1101_REG_TYPE_FIFO, .reg_access_type = CC1101_REG_ACCESS_TYPE_WRITE_ONLY },
    /************************** RX FIFO - Read Only ************************/
    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_TXFIFO_RXFIFO, .reg_type = CC1101_REG_TYPE_FIFO, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_ONLY },

    /**************************** Status Registers ******************************/
    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_SRES_PARTNUM, .reg_type = CC1101_REG_TYPE_STATUS, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_ONLY },
    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_SFSTXON_VERSION, .reg_type = CC1101_REG_TYPE_STATUS, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_ONLY },
    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_SXOFF_FREQEST, .reg_type = CC1101_REG_TYPE_STATUS, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_ONLY },
    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_SCAL_LQI, .reg_type = CC1101_REG_TYPE_STATUS, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_ONLY },
    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_SRX_RSSI, .reg_type = CC1101_REG_TYPE_STATUS, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_ONLY },
    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_STX_MARCSTATE, .reg_type = CC1101_REG_TYPE_STATUS, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_ONLY },
    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_SIDLE_WORTIME1, .reg_type = CC1101_REG_TYPE_STATUS, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_ONLY },
    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_WORTIME0, .reg_type = CC1101_REG_TYPE_STATUS, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_ONLY },
    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_SWOR_PKTSTATUS, .reg_type = CC1101_REG_TYPE_STATUS, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_ONLY },
    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_SPWD_VCO_VC_DAC, .reg_type = CC1101_REG_TYPE_STATUS, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_ONLY },
    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_SFRX_TXBYTES, .reg_type = CC1101_REG_TYPE_STATUS, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_ONLY },
    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_SFTX_RXBYTES, .reg_type = CC1101_REG_TYPE_STATUS, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_ONLY },
    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_SWORRST_RCCTRL1_STATUS, .reg_type = CC1101_REG_TYPE_STATUS, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_ONLY },
    { .reg_addr = CC1101_INTERNAL_REG_ADDRESS_SNOP_RCCTRL0_STATUS, .reg_type = CC1101_REG_TYPE_STATUS, .reg_access_type = CC1101_REG_ACCESS_TYPE_READ_ONLY },
    /************************************************************************/


    { .reg_addr = 0xFF, .reg_type = CC1101_REG_TYPE_MARKER, .reg_access_type = CC1101_REG_ACCESS_TYPE_UNKNOWN },
};